//GET all
GET http://localhost:5205/games

###
//GET One data
GET http://localhost:5205/games/1

###
//POST new data
POST http://localhost:5205/games 
Content-Type: application/json

{
   
    "Name": "FIFA 28",
    "genreId": 3,
    "Price": 110.99,
    "ReleaseDate": "1994-02-12"
}

###
//PUT new data
PUT http://localhost:5205/games/2
Content-Type: application/json

{
    "Name": "Streey Fighter II Turbo 2",
    "GenreId": 2,
    "Price": 29.99,
    "ReleaseDate": "1991-07-15"
}


###
//DELETE data
DELETE http://localhost:5205/games/1